import 'package:flutter/material.dart';
import '../domain/models.dart';
import '../data/avaliation_store.dart';
import '../ui/common.dart';

class NotificationsPage extends StatelessWidget {
  const NotificationsPage({super.key});
  @override Widget build(BuildContext context){final s=AppScope.of(context);final entries=s.minhasNotificacoes;return AppPage(title:'Notificações',subtitle:'Suas atualizações recentes',actions:[TextButton(onPressed:()=>runAction(context,()=>s.marcarTodasLidas()),child:const Text('Lidas todas'))],child:entries.isEmpty?const EmptyState('Nenhuma notificação','Suas atualizações aparecerão aqui.',icon:Icons.notifications_none):Column(children:[for(final n in entries)...[Panel(child:InkWell(onTap:()async{await runAction(context,()=>s.marcarLida(n.id));if(!context.mounted)return;if(n.tipo==TipoNotificacao.conviteTurma && n.referenciaId!=null){final c=s.encontrar(s.convites,n.referenciaId!,(e)=>e.id);if(c.estudanteId==s.uid && c.status==StatusConvite.pendente){final accept=await confirmAction(context,'Convite para turma','Deseja participar de ${s.turma(c.turmaId).nome}?',confirm:'Aceitar');if(context.mounted)await runAction(context,()=>s.responderConvite(c.id,accept));}}},child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(backgroundColor:AppColors.primary.withValues(alpha:.10),child:Icon(_notificationIcon(n.tipo),color:AppColors.primary,size:20)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(n.titulo,style:const TextStyle(fontWeight:FontWeight.w800))),if(!n.lida)Container(width:7,height:7,decoration:const BoxDecoration(color:AppColors.primary,shape:BoxShape.circle))]),const SizedBox(height:5),Text(n.mensagem,style:const TextStyle(fontSize:13)),const SizedBox(height:7),Text(dateLabel(n.dataCriacao),style:const TextStyle(fontSize:11,color:AppColors.muted))]))]))),const SizedBox(height:10)]]));}
  IconData _notificationIcon(TipoNotificacao tipo)=>switch(tipo){TipoNotificacao.conviteTurma=>Icons.group_add_outlined,TipoNotificacao.novaAvaliacao=>Icons.assignment_outlined,TipoNotificacao.prazoProximo=>Icons.schedule,TipoNotificacao.resultadoDisponivel=>Icons.verified_outlined,TipoNotificacao.novaResposta=>Icons.move_to_inbox_outlined,TipoNotificacao.publicacaoEncerrada=>Icons.event_busy_outlined,TipoNotificacao.sistema=>Icons.info_outline};
}

class ProfilePage extends StatelessWidget {const ProfilePage({super.key});@override Widget build(BuildContext context)=>const AppPage(title:'Perfil',subtitle:'Dados e preferências pessoais',child:ProfileContent());}
class ProfileContent extends StatelessWidget {
  const ProfileContent({super.key});
  @override Widget build(BuildContext context){final s=AppScope.of(context);final u=s.usuario;final c=s.configuracao;return Column(children:[const SizedBox(height:12),CircleAvatar(radius:42,backgroundColor:AppColors.primary.withValues(alpha:.12),child:Text(u.nome.substring(0,1).toUpperCase(),style:const TextStyle(fontSize:32,fontWeight:FontWeight.w800,color:AppColors.primary))),const SizedBox(height:14),Text(u.nome,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:21)),const SizedBox(height:4),Text(u.email,style:const TextStyle(color:AppColors.muted,fontSize:13)),const SizedBox(height:28),SectionTitle('Dados pessoais',trailing:TextButton(onPressed:()=>openPage(context,const EditProfilePage()),child:const Text('Editar'))),Panel(child:Column(children:[InfoRow('Nome',u.nome),const Divider(),InfoRow('E-mail',u.email),const Divider(),InfoRow('Perfil',s.professor?'Professor':'Estudante'),const Divider(),InkWell(onTap:()=>openPage(context,const ChangePasswordPage()),child:const Padding(padding:EdgeInsets.symmetric(vertical:7),child:Row(children:[Icon(Icons.lock_outline,size:18,color:AppColors.primary),SizedBox(width:10),Expanded(child:Text('Alterar senha',style:TextStyle(fontWeight:FontWeight.w600))),Icon(Icons.chevron_right,color:AppColors.muted)])))])),const SizedBox(height:22),const SectionTitle('Preferências de notificação'),Panel(padding:EdgeInsets.zero,child:Column(children:[SwitchListTile(title:const Text('Notificações ativas'),subtitle:const Text('Avisos disponíveis no aplicativo'),value:c.notificacoesAtivas,onChanged:(v)=>runAction(context,()=>s.atualizarConfiguracao((c)=>c.notificacoesAtivas=v))),const Divider(height:1),SwitchListTile(title:const Text('Novas avaliações'),value:c.notificacaoNovaAvaliacao,onChanged:(v)=>runAction(context,()=>s.atualizarConfiguracao((c)=>c.notificacaoNovaAvaliacao=v))),const Divider(height:1),SwitchListTile(title:const Text('Prazos próximos'),value:c.notificacaoPrazo,onChanged:(v)=>runAction(context,()=>s.atualizarConfiguracao((c)=>c.notificacaoPrazo=v))),const Divider(height:1),SwitchListTile(title:const Text('Resultados disponíveis'),value:c.notificacaoResultado,onChanged:(v)=>runAction(context,()=>s.atualizarConfiguracao((c)=>c.notificacaoResultado=v)))])),const SizedBox(height:12),Panel(padding:EdgeInsets.zero,child:SwitchListTile(secondary:const Icon(Icons.dark_mode_outlined,color:AppColors.primary),title:const Text('Tema escuro'),value:c.temaEscuro,onChanged:(v)=>runAction(context,()=>s.atualizarConfiguracao((c)=>c.temaEscuro=v)))),const SizedBox(height:22),SizedBox(width:double.infinity,child:AppButton('Sair da conta',outlined:true,danger:true,icon:Icons.logout,onPressed:()async{if(await confirmAction(context,'Sair da conta','Deseja encerrar sua sessão?',confirm:'Sair')){if(context.mounted){await runAction(context,()=>s.sair());AppNav.selected.value=0;}}})),const SizedBox(height:14),const Text('Protótipo local • Dados de demonstração',style:TextStyle(fontSize:11,color:AppColors.muted))]);}
}
class EditProfilePage extends StatefulWidget{const EditProfilePage({super.key});@override State<EditProfilePage> createState()=>_EditProfilePageState();}
class _EditProfilePageState extends State<EditProfilePage>{late final TextEditingController nome,email;@override void initState(){super.initState();final u=AppScope.of(context).usuario;nome=TextEditingController(text:u.nome);email=TextEditingController(text:u.email);}@override void dispose(){nome.dispose();email.dispose();super.dispose();}@override Widget build(BuildContext context){final s=AppScope.of(context);return AppPage(title:'Dados pessoais',child:Column(children:[AppField('Nome',controller:nome),const SizedBox(height:16),AppField('E-mail',controller:email),const SizedBox(height:24),AppButton('Salvar alterações',onPressed:()async{final ok=await runAction(context,()=>s.atualizarPerfil(nome.text,email.text),success:'Perfil atualizado.');if(mounted && ok==null)Navigator.pop(context);})]));}}
class ChangePasswordPage extends StatefulWidget{const ChangePasswordPage({super.key});@override State<ChangePasswordPage> createState()=>_ChangePasswordPageState();}
class _ChangePasswordPageState extends State<ChangePasswordPage>{final antiga=TextEditingController(),nova=TextEditingController();@override void dispose(){antiga.dispose();nova.dispose();super.dispose();}@override Widget build(BuildContext context){final s=AppScope.of(context);return AppPage(title:'Alterar senha',child:Column(children:[AppField('Senha atual',controller:antiga,obscure:true),const SizedBox(height:16),AppField('Nova senha',controller:nova,obscure:true),const SizedBox(height:24),AppButton('Salvar nova senha',onPressed:()async{await runAction(context,()=>s.alterarSenha(antiga.text,nova.text),success:'Senha atualizada.');if(mounted)Navigator.pop(context);})]));}}